name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: "pocterraform.azurecr.io/pocterraform/be"
        username: "00c9b931-360b-4a7b-8403-dbe7a63bdfdc"
        password: "_018Q~sG8Q7OjrVHQ._ADkRsw8.~H-TWqSDpxc6f"

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/bpn-image-name:${{ github.sha }}

    - name: Push image to Azure Container Registry
      run: |
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/bpn-image-name:${{ github.sha }}
